### ISSUE TITLE
game  keeps crashing

### ISSUE THREAD

**Issue by Eljonathan214** [icebound777/PMR-SeedGenerator#107]
when i attack enemy it crashing

**Comment by Pronyo-Chan** [comment]
Hi! I assume you're playing on Project 64 and Windows 11? This is a known issue that also affects the original game, it's non a randomizer issue. Playing with Project 64 on W11 constantly crashes. You should be able to play with a different emulator such as Bizhawk Simple64, or any other emulator that is based on Mupen.
