### ISSUE TITLE
Gusty Gulch gate not opening even after bow is unlocked

### ISSUE THREAD

**Issue by mccaslin1018** [icebound777/PMR-SeedGenerator#20]
im not entirely sure where to put this but when i try to go to gusty gulch it says i can't open the gate even though i unlocked bow from somewhere else

**Comment by Pronyo-Chan** [comment]
The requirement to open the gate is advancing the chapter's progress like in the original game, which means going to the top of the mansion using Boo's Portrait and viewing the Bow / Bootler cutscene. Acquiring Bow in a random location does not open the gate.
