### ISSUE TITLE
Crash when getting Parakarry

### ISSUE THREAD

**Issue by blueYOSHI9000** [icebound777/PMR-SeedGenerator#23]
If you talk to Parakarry and deny his request to join then the textbox won't disappear. If you talk to Parakarry again the game crashes.
[Twitch Clip](https://clips.twitch.tv/PoliteGoodShallotOpieOP-HvG09M3BvR0OAM7-)
[Seed](https://pm64randomizer.com/seed?id=2710046537), generated on 0.9.1
[Save-state](https://drive.google.com/file/d/1f4kk5R54QREtgQDWmm1Fh8D1csgM2IED/view?usp=sharing), Emulator is Project 64 3.0.1

**Comment by icebound777** [comment]
fixed on mod repo, will be part of next release

**Comment by icebound777** [comment]
Fix released as part of v. 0.10.0
