### ISSUE TITLE
Option to randomize music (swap themes randomly)

### ISSUE THREAD

**Issue by geekley** [icebound777/PMR-SeedGenerator#54]
It would be cool to be able to randomize music. Not in a crazy absurd way, but following a certain logic; where music is in separate pools per category, and only swapped within the same pool. Something like this:

- **Action pool**: upbeat event themes, e.g.: Normal Battle, Mid-boss Battle, Minigame, Fuzzies, Monty-Moles, etc.
- **Boss pool**: all battles against a specific character, e.g. Bowser, Bosses, The Master, Jr Troopa, etc
- **Character pool**: all themes of specific characters, e.g. bosses outside of battle, Peach, Twink, flower characters
- **Field pool**: all areas where you can battle normal enemies, e.g. Pleasant Path, etc
- **Safe pool**: all villages (except Toad Town) and other safe areas (e.g. Shooting Star Summit, Sun Tower, etc)
- **Establishment pool**: transition themes in subareas of Toad Town, e.g. Merlon, Dojo, Rowf, Tayce T., etc., also maybe Club 64

Some other music would be unaffected, such as:
- Toad Town (regular and Shy Guy version)
- New partner, chapter completed, maybe star spirits theme?
- themes that don't loop, of course: e.g. Intros, Credit, Cutscenes like train, Bowser castle collapsing, etc

**Comment by icebound777** [comment]
Music rando is planned, although it'll most likely not have as many options to choose from. It's probably one of the most requested features on the rando discord, and will be tackled soon

**Comment by icebound777** [comment]
Implemented as of 0.21.0
