### ISSUE TITLE
Prologue Jr Troopa Health Overflow

### ISSUE THREAD

**Issue by stllr927** [icebound777/PMR-SeedGenerator#60]
I'm not sure if this is the correct place for this issue, but when fighting Jr Troopa in the prologue, he does not die until he's done his special attack. This would be fine, except if you have a Volt Shroom enabled and he does his special attack at 0HP, he will take 1 damage and his health will overflow to 255. I'm fully aware this is a randomizer exclusive bug that can simply be avoided by not using a Volt Shroom in this fight, but I figured that it was something worth pointing out. His health is represented as 250 in the video because I attacked him with bombette before I realized what had happened. He is also hovering directly above me because of another glitch with the Volt Shroom. Video attached.

https://user-images.githubusercontent.com/22407114/200372195-2abac02d-c77f-4ea0-ab0d-70ed40a02fb9.mp4

**Comment by icebound777** [comment]
Thanks for the report!
We are aware of this issue with the rando. Prologue Jr. Troopa reacts rather weirdly to electric and blast / fire type damage.
Fixing this is currently low priority

**Comment by icebound777** [comment]
Fixed as of version 0.18.1
