### ISSUE TITLE
Missing Star Hunt Stars?

### ISSUE THREAD

**Issue by stllr927** [icebound777/PMR-SeedGenerator#83]
Hello PMR Team! I'm writing what I'm assuming is a bug report, and not collective delirium. 

My girlfriend & I have done two 120 Star Hunt rando seeds together over the past week or so, and both times we've come up with exactly 119 Stars. Upon hitting the 119 wall and feeling like we've run out of checks (with the tracker to confirm that we've actually checked everything), we've opened the spoiler log and individually gone through every check listed to have a Power Star attached to them, and found them all to be collected both times, on both of our copies (we play the same seed at the same time taking different routes). This leads us to believe that there could be an issue with the star counter itself, since we've even counted the number of times a Power Star item shows up on the spoiler log when searched for, and it lists 120 locations, all of which we've checked. 

I don't have her save files currently (I'm sure I can get them if need be), but below I have linked my save file, with the two associated spoiler log webpages, settings strings, & spoiler log text files (in case the website auto-deletes them before the issue is able to be fixed), along with all shared star locations between the two seeds, and the information of the emulator I'm playing on.

Please let us know if there's anything we could've done differently, and thank you for looking into this.

### Seed 1:
Link: https://pm64randomizer.com/seed?id=4232795305
ID: 4232795305 - Items: Nutty Cake, Goomnut, Jelly Shroom, Lucky Star
Settings String: (iIVEJNSPf2KDXl3RBg2a11OM)(gb1f1p1s1rm2)(pSaRn1x1(pGktpbwsl))(qh3SiPZgCELt0dQFVo)(dd1ca1m1kshq125r1zw7lt1Yp1B)(mc120h10f5b3s0j-1a-1iRn2x2)(om4btwCrps65796o1DX?120!120Y)(cm0p00g00k00o00a00b00w00s00l00x0n0e0y0c0trhu-1j)gRx)

Spoiler Log:
[4232795305_spoiler.txt](https://github.com/icebound777/PMR-SeedGenerator/files/11498081/4232795305_spoiler.txt)

### Seed 2:
Link: https://pm64randomizer.com/seed?id=1892814210
ID: 1892814210 - Items: Power Bounce, Super Jump, Mega Quake, Bland Meal

Settings String: (iIVEJNSPf2KDXl3RBg2a11OM)(gb1f1p1s1rm2)(pSaRn1x1(pGktpbwsl))(qh3SiPZgCELt0dqFVO)(dd1Ca1m1kshq100r2zw7lt1Yp1b)(mc100h10f5b3s0j0a-1iRn3x3)(om4btwCrps65796o0DX?120!120Y)(cm7p20g20k20o20a20b20w20s20l20x2n2e2y2c0tRhu-1j)gRx)

Spoiler Log:
[1892814210_spoiler.txt](https://github.com/icebound777/PMR-SeedGenerator/files/11498106/1892814210_spoiler.txt)

### Save Files:
[incomplete star hunt save files.zip](https://github.com/icebound777/PMR-SeedGenerator/files/11498700/incomplete.star.hunt.save.files.zip)

The attached save file contains the saves of both Star Hunt seeds from my perspective.
**Seed 1**'s save file can be found in **Slot 4**.
**Seed 2**'s save file can be found in **Slot 3**.

### Shared Star Locations, As Named by the Spoiler Logs:
**Goomba Region**
- *Bottom of the Cliff - Upper Ledge* within the *Goomba Region* region
- *Jr. Troopas Playground - Bush Top Left* within the *Goomba Region* region
- *Marios House - Luigi Koopa Koot Favor* within the *Goomba Region* region

**Toad Town**
- *Gate District - Russ T. Dictionary Reward* within the *Toad Town* region
- *Gate District - Miss T. Letter Reward* within the *Toad Town* region
- *Southern District - Bub-ulb Gift* within the *Toad Town* region
- *Residental District - Storeroom Item 1* within the *Toad Town* region
- *Port District - Poet Melody Reward* within the *Toad Town* region
- *Short Elevator Room (B1) - Yellow Block Center* within the *Toad Town Tunnels* region
- *Merluvlees House - Merlows Rewards 4* within the *Shooting Star Summit* region

**Chapters 1 & 2 Areas**
- *Path to Fortress 1 - X On Ground 2* within the *Koopa Region* region
- *Train Station - Bush 2* within the *Mt Rugged* region
- *Mt Rugged 4 - Hidden Cave Chest* within the *Mt Rugged* region
- *Mt Rugged 4 - Yellow Block Top Right* within the *Mt Rugged* region
- *E1 Nomadimouse - Nomadimouse Letter Reward* within the *Dry Dry Desert* region

**Chapters 3, 4 & 5 Areas**
- *Wasteland Ascent 1 - Yellow Block 2* within the *Gusty Gulch* region
- *GRN Treadmills/Slot Machine - In Chest* within the *Shy Guys Toybox* region
- *Village Cove - Hidden Panel* within the *Jade Jungle* region
- *Village Buildings - Red Yoshi Kid Letter Reward* within the *Jade Jungle* region
- *SW Jungle (Super Block) - Underwater 3* within the *Jade Jungle* region

**Chapters 6 & 7 Areas**
- *(SE) Briar Platforming - Left Side Vine* within the *Flower Fields* region
- *Shiver City Center - Snowmen Gift 2* within the *Shiver Region* region
- *Red Key Room - In Chest* within the *Crystal Palace* region
- *P-Down, D-Up Room - In Chest* within the *Crystal Palace* region

There are also a few Shared Star Locations that aren't quite identical, but have similarities, such as being sold by Rowf or Rip Cheato, or given out as a reward by Koopa Koot, but none of these stars occupied the exact same slot. However if it's none of the above Shared Star Locations I think it's likely that it could be one of these. Also in Seed 1 there was a check in which a Power Star and a Trap were collected at the same time within Jr. Troopa's Playground, and we speculated initially that this caused the issue. Hopefully these are good to go off of.

### System Information:
OS: Windows 10
Emulator: M64Py (v0.2.5)
Mupen64Plus core version: v2.5.9

I would put the MD5 Checksum here but I can't find a way to calculate it for N64 ROMs. If this is information you'd be looking for and you know how to do it, please respond to this thread with instructions, and I will verify the checksum for the base ROM along with both rando seeds (assuming generating a rando changes the checksum).

Thank you very much for your time, and if you have any suggestions for workarounds please let us know, as we'd love to see the ending of a Star Hunt run sometime. Also this is absolutely not part of the request but if you wanted to put another feature on the roadmap, it would be really cool to see Merluvlee give hints for where the remaining power stars are.

**Comment by Pronyo-Chan** [comment]
Hi! Thank you for the detailed report. I have played with your first seed's savefile and found the star! 
![image](https://github.com/icebound777/PMR-SeedGenerator/assets/12000950/b1845774-b818-440b-9c3d-5464f4122ca7)

There is indeed a small bug, in the spoiler log. It says front-right tree but this one is left as you can see. We will fix it in a future release.

I didn't test the second seed as it is quite consuming, but if you really wanna dig in, I suggest using the ingame map tracker. Pickup every item to mark every map area as completed and you should find the remaining star eventually (that's how I found the desert star in your savefile).


Thank you!

**Comment by icebound777** [comment]
Hey there @stllr927, thank you for the issue!

Mind checking the following locations for us on your seeds and save files?
-> Seed 1: Oasis, left-most tree (as shown by @Pronyo-Chan )
-> Seed 2: Dry Dry Outpost shop, item third from the left

**Comment by stllr927** [comment]
Oh my god, I'm so terribly sorry for the inconvenience. I knew there was a very real possibility for this to be human error with everything involved, but after the second rando in a row that this had happened, I was in utter disbelief that this type of coincidence was possible. Sure enough though, I booted up both seeds and sure enough both stars were there. Thank you for being courteous in your responses, and for also informing us about the in-game tracker. Have a wonderful evening.
