### ISSUE TITLE
(Suggestion) Allow Manual Raising Of Max BP

### ISSUE THREAD

**Issue by coltmay** [icebound777/PMR-SeedGenerator#88]
I previously played this randomizer occasionally with cheats enabled to increase my the BP beyond 30.
With the new updates, said cheats are broken.

In order to better utilize badge synergy and make more interesting low HP runs, **could we possibly allow a raising of the BP cap manually in the difficulty settings**?

I believe the only practical thing to contend with would be ensuring Mario's level never extends beyond what it would be at the maximum BP range (i.e. ensuring he is still level 10 even with 50+ BP, all other starting stats vanilla).

Love the randomizer, by the way!  One of the best randomizers I've played, by a wide margin.

**Comment by icebound777** [comment]
Glad you enjoy the rando!

Currently we have no plans for increasing the maximum values for Mario's HP, FP or BP.
I don't rule this out as a possible setting in the future, but it is not on our current roadmap.

If you don't mind, could you tell me which cheats exactly you used to increase your BP beyond the max?
Maybe we can get that adjusted to the current state of the randomizer with a little effort in the meantime.

**Comment by coltmay** [comment]
Infinite BP by Hyperhacker via gamehacking(dot)org

Note from the creator:
Finally, an Infinite BP code!
Apparently the game doesn't keep remaining BP in memory, since all it needs to do is subtract total from all your badges.  This code makes it read your total as 32,767 instead. You can change the false total by changing the last 4 digits, but keep in mind if this number minus the total BP cost of all your badges is zero or less, you still won't be able to equip any

Note also, the remaining BP display will show various crap, just ignore it. Similarly, badges you normally wouldn't have enough BP for will be grayed out, but you can equip them anyway.

Finally, note the D1-codes. This game switches code in and out of the same area of memory a lot, so it's important to make sure we only modify the BP code and not some other stuff.

```
D12473EC 8223
812473EC 2403
D12473EE 0008
812473EE 7FFF
```

**Comment by icebound777** [comment]
Mhhh, an infinite BP cheat should be way easier than that.
Just locking the BP to 99 in the player data should do the trick.
`8010F298 63` on RetroArch
or
RDRAM `10F298 63` on BizHawk
work for me.
Could you try these, and if they don't work let me know which emu / flash cartridge you're using?

**Comment by coltmay** [comment]
Using an EverDrive, the RetroArch code provided does in fact allow me to set the BP to whatever threshold I want.

Thanks for going above and beyond to test and provide those codes, I know this was totally out of scope for the randomizer.

Closing issue, since this is not in the current roadmap.  Feel free to reopen if you disagree.
